"""Rename invoice_category value saas_invoice -> overseas_invoice.

Revision ID: 0017_rename_saas_to_overseas
Revises: 0016_add_scraper_account_fields
Create Date: 2026-05-10

The v1.2.0 Track A taxonomy mixed conceptual levels: ``saas_invoice`` was a
purchase-type label while the other four categories are document-formality
labels (Chinese VAT invoice, informal receipt, proforma quote, anything
else). Rename ``saas_invoice`` to ``overseas_invoice`` (境外票据 —
non-Chinese formal invoice) so every category is a document-type concept.

Data-only migration: the column type is already ``VARCHAR(32)`` with
no CHECK constraint, so we just rewrite row values. No schema change,
no FTS5 rebuild required (the FTS row text is regenerated by the
existing triggers on UPDATE).
"""
from __future__ import annotations

from alembic import op


revision = "0017_rename_saas_to_overseas"
down_revision = "0016_add_scraper_account_fields"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        "UPDATE invoices SET invoice_category = 'overseas_invoice' "
        "WHERE invoice_category = 'saas_invoice'"
    )


def downgrade() -> None:
    op.execute(
        "UPDATE invoices SET invoice_category = 'saas_invoice' "
        "WHERE invoice_category = 'overseas_invoice'"
    )
